### PR TITLE
Update Journalator.toc

### PR DESCRIPTION
**Pull request by nanjuekaien1**
^_^

### CODE REVIEW

**Comment by nanjuekaien1** [comment]
Missing inside 
L["SEND_COST"] = "邮资"
L["RECEIVED"] = "已收件"

**Comment by plusmouse** [comment]
I've added the changes (tweaked slightly) to the latest alphas.

**Comment by nanjuekaien1** [comment]
L["TRADES"] = "交易"
L["TRADES_TITLE"] = "Journalator - 交易"

**Comment by plusmouse** [comment]
Done. Thanks.
image

**Comment by plusmouse** [comment]
Its not that, a lot of other people are affected too. Using the website directly seems to work around the issue.

**Pull request closed without merging**
