### PR TITLE
Update Info.xml

### PR DESCRIPTION
**Pull request by nanjuekaien1**
thanks

### CODE REVIEW

**Comment by nanjuekaien1** [comment]
--zhCN

L["ALL_FACTIONS"] = "所有阵营"
L["ALL_REALMS"] = "所有服务器"
L["ALL_TIME"] = "所有时间"
L["AMOUNT_SOLD"] = "销售金额"
L["AMOUNT_UNSOLD"] = "未售出数量"
L["CANCELLED"] = "取消"
L["COMPUTE_STATISTICS"] = "计算统计"
L["CONFIG_BASIC_OPTIONS_TEXT"] = "启用功能的基本选项。"
L["CONFIG_GROUP_JUNK"] = "在 \"商人\" 选项中对垃圾物品进行分类"
L["CONFIG_SHOW_DETAILED_STATUS"] = "在主体的状态文本中显示更多详细信息。"
L["CONFIG_SHOW_MINIMAP_ICON"] = "显示小地图图标"
L["CONFIG_TOOLTIP_FAILURES"] = "在工具提示中显示物品的拍卖失败次数。"
L["CONFIG_TOOLTIP_LAST_BOUGHT"] = "在工具提示中显示您购买物品的最后拍卖价格。"
L["CONFIG_TOOLTIP_LAST_SOLD"] = "在工具提示中显示您拍卖的物品的最后售价。"
L["CONFIG_TOOLTIP_SALE_RATE"] = "在工具提示中显示您的物品销售率。"
L["CONFIG_VENDORING"] = "商人"
L["DAILY_PROFIT"] = "每日利润"
L["DEPOSIT"] = "保证金"
L["DETAILED_STATUS"] = "总销售: %s | AH 费用: %s | 保证金: %s | 购买: %s | 净利润: %s"
L["ENGAGE_HEADER"] = "与 Journalator 互动"
L["EXPIRED"] = "过期"
L["FAILURES"] = "失败"
L["FAILURES_TITLE"] = "Journalator - 失败"
L["FINISHED_COMPUTING_STATISTICS"] = "完成统计计算。"
L["IN"] = "在"
L["IN_INCLUDING_AH_CUT"] = "在 (包含 AH 竞价)"
L["INFO_TITLE"] = "Journalator - 信息"
L["INVOICES"] = "账本"
L["INVOICES_TITLE"] = "Journalator - 记账本"
L["JOURNALATOR"] = "Journalator"
L["JUNK"] = "垃圾"
L["LAST_3_MONTHS"] = "过去 3 个月"
L["LAST_6_MONTHS"] = "过去 6 个月"
L["LAST_BOUGHT"] = "最后购买"
L["LAST_DAY"] = "最后一天"
L["LAST_HOUR"] = "最后一小时"
L["LAST_MONTH"] = "上个月"
L["LAST_SOLD"] = "最后售出"
L["LAST_WEEK"] = "上周"
L["LAST_YEAR"] = "去年"
L["LOADING_X_X"] = "正在加载 %d/%d"
L["MEAN_PRICE"] = "平均价格"
L["MINIMAP_ICON"] = "小地图图标"
L["MONTHLY_PROFIT"] = "月利润"
L["MULTIPLE_BUYERS"] = "多个买家"
L["MULTIPLE_SELLERS"] = "多个卖家"
L["OUT"] = "出"
L["PLAYER"] = "玩家"
L["POSTING"] = "发布"
L["POSTING_TITLE"] = "Journalator - 发布"
L["SALE_RATE"] = "销售率"
L["SALE_RATES"] = "销售率"
L["SALE_RATES_TITLE"] = "Journalator - 销售率"
L["SOME_REALMS"] = "一些服务器"
L["SOURCE"] = "来源"
L["STATISTICS"] = "统计"
L["TIME_ELAPSED"] = "已用时间"
L["TOTAL"] = "总计"
L["TYPE_OF_FAILURE"] = "失败类型"
L["UNIT_PRICE_EXCLUDING_AH_CUT"] = "单价 (不包含 AH 竞价)"
L["VENDORING"] = "商人"
L["VENDORING_TITLE"] = "Journalator - 商人"
L["YOU_GAINED_X_WITH_XX"] = "你获得了 %s, 有 %s 买进和 %s 卖出。"
L["YOU_LOST_X_WITH_XX"] = "你损失了 %s, 有 %s 买进和 %s 卖出"

**Comment by plusmouse** [comment]
Awesome

**Comment by nanjuekaien1** [comment]
L["AMOUNT_SOLD"] = "售出数"
L["AMOUNT_UNSOLD"] = "未售出数"
L["MEAN_PRICE"] = "出售价/个"
L["OUT"] = "支出"
L["SALE_RATES"] = "销量"
L["SALE_RATES_TITLE"] = "Journalator - 销量"

Thanks

**Comment by plusmouse** [comment]
Done

**Comment by nanjuekaien1** [comment]
L["LAST_DAY"] = "前天"
L["LAST_HOUR"] = "一小时前"
L["LAST_3_MONTHS"] = "过去3个月"
L["LAST_6_MONTHS"] = "过去6个月"

**Comment by nanjuekaien1** [comment]
L["CONFIG_TOOLTIP_LAST_BOUGHT"] = "在工具提示中显示您购买物品的最后价格。"
L["YOU_GAINED_X_WITH_XX"] = "你获得了 %s, 有 %s 购买和 %s 出售。"
L["YOU_LOST_X_WITH_XX"] = "你损失了 %s, 有 %s 购买和 %s 出售。"

**Comment by nanjuekaien1** [comment]
www.curseforge.com/wow/addons/journalator/localization  
Missing inside "LOOTING"
 L["LOOTING"] = "拾取"

**Comment by plusmouse** [comment]
Done 👍

**Pull request merged**
